services:
  database:
    image: postgres:18.3-alpine3.22
    restart: always
    shm_size: 128mb
    ports:
      - "5432:5432" # This was required for the port to be accessible on the host
    volumes:
      - type: volume 
        source: pg-data
        target: /var/lib/postgresql
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

  cache:
    image: redis:8.6-alpine
    ports:
      - "6379:6379"
    volumes:
      - type: volume
        source: redis-data 
        target: /data


volumes:
  pg-data:
  redis-data: